services:
  - type: web
    name: controle-caixa
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: controle-caixa-db
          property: connectionString

databases:
  - name: controle-caixa-db
    plan: free
